project: 
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "Engineering Computation"
  subtitle: "A Tutorial for Beginners in Computation for Applied Mechanics"
  author: "Serhat Beyenir"
  date: last-modified
  date-format: "D MMMM YYYY"
  #downloads: [pdf]
  sidebar:
    align: left
    style: floating
    collapse-level: 2
    pinned: false
  page-footer:
    left: © 2025 <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
    right: |
      Built with <a href="https://quarto.org"> Quarto {{< version >}}</a>
  chapters:
    - index.qmd
    - part: Beginning
      chapters:
      - python_tutorial.qmd
      - SI_Units.qmd
    - part: Making progress
    - part: Going forward
      chapters:
      - review.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    toc: true
    collapse: true
    theme:
      - cosmo
      - brand
  pdf:
    #latex-engine: xelatex  # or pdflatex, if preferred
    documentclass: book #scrreprt
    code-overflow: wrap
    toc-title: Contents
    lot: true
    lof: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
